/**
 * Pure builders for the nightly low-stock digest email. English content,
 * off-catalog (server email is never translated). No em-dash anywhere.
 * Assumes `items` is non-empty when called.
 */

export interface LowStockItem {
  name: string;
  currentStockQty: number;
  reorderThreshold: number;
  unit: 'g' | 'ml' | 'piece';
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Plain-text body listing each low-stock ingredient. */
export function buildLowStockText(cafeName: string, items: LowStockItem[]): string {
  const lines = [
    cafeName,
    'Low stock alert',
    '',
    ...items.map(
      (i) =>
        `${i.name}: ${i.currentStockQty} ${i.unit} (reorder at ${i.reorderThreshold} ${i.unit})`
    ),
    '',
    'Generated by kodapos',
  ];
  return lines.join('\n');
}

/** HTML body: a heading plus a table of the low-stock ingredients. */
export function buildLowStockHtml(cafeName: string, items: LowStockItem[]): string {
  const rows = items
    .map(
      (i) =>
        `<tr><td>${escapeHtml(i.name)}</td><td>${i.currentStockQty} ${i.unit}</td>` +
        `<td>${i.reorderThreshold} ${i.unit}</td></tr>`
    )
    .join('');
  return (
    `<h2>Low stock alert</h2>` +
    `<p>${escapeHtml(cafeName)}</p>` +
    `<table>` +
    `<thead><tr><th>Ingredient</th><th>Current</th><th>Reorder at</th></tr></thead>` +
    `<tbody>${rows}</tbody>` +
    `</table>` +
    `<p>Generated by kodapos</p>`
  );
}
