// Pure, dependency-free shift-summary builders. The emailed summary content is
// ALWAYS English and kept out of the i18n catalog. No em-dash and no double-hyphen
// anywhere in the generated text/html (use commas, periods, parentheses instead).
//
// These take a plain typed input mirroring the shift numbers produced by
// `shifts.summaryData`. No Convex/ctx/client imports.

export interface ShiftSummaryData {
  cafeName: string;
  openedAt: number;
  closedAt: number;
  salesTotalIDR: number;
  cashSalesIDR: number;
  qrisSalesIDR: number;
  openingFloatIDR: number;
  expectedCashIDR: number;
  countedCashIDR: number | null;
  varianceIDR: number | null;
}

/** Pure IDR formatter: `Rp ` + thousands separators, no decimals. */
function formatIDR(n: number): string {
  const sign = n < 0 ? '-' : '';
  const abs = Math.round(Math.abs(n)).toString();
  const grouped = abs.replace(/\B(?=(\d{3})+(?!\d))/g, '.');
  return `${sign}Rp ${grouped}`;
}

function formatDate(ts: number): string {
  return new Date(ts).toLocaleString('en-GB');
}

/** Variance wording with an Over/Short suffix, no dash. Null or zero gets no suffix. */
function varianceText(variance: number | null): string {
  if (variance === null) return formatIDR(0);
  const base = formatIDR(variance);
  if (variance > 0) return `${base} (Over)`;
  if (variance < 0) return `${base} (Short)`;
  return base;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Plain-text English shift summary. */
export function buildShiftSummaryText(d: ShiftSummaryData): string {
  const out: string[] = [];

  out.push(d.cafeName);
  out.push('Shift summary');
  out.push(formatDate(d.closedAt));
  out.push(`Opened: ${formatDate(d.openedAt)}`);
  out.push(`Closed: ${formatDate(d.closedAt)}`);
  out.push('');

  out.push(`Sales total   ${formatIDR(d.salesTotalIDR)}`);
  out.push(`Cash sales   ${formatIDR(d.cashSalesIDR)}`);
  out.push(`QRIS sales   ${formatIDR(d.qrisSalesIDR)}`);
  out.push('');

  out.push(`Opening float   ${formatIDR(d.openingFloatIDR)}`);
  out.push(`Expected cash   ${formatIDR(d.expectedCashIDR)}`);
  out.push(
    `Counted cash   ${d.countedCashIDR !== null ? formatIDR(d.countedCashIDR) : formatIDR(0)}`
  );
  out.push(`Variance   ${varianceText(d.varianceIDR)}`);
  out.push('');

  out.push('Generated by kodapos');

  return out.join('\n');
}

/** HTML English shift summary (a simple table layout). */
export function buildShiftSummaryHtml(d: ShiftSummaryData): string {
  const row = (label: string, value: string, bold = false) => {
    const style = bold ? ' style="font-weight:bold"' : '';
    return `<tr${style}><td>${escapeHtml(label)}</td><td align="right">${escapeHtml(value)}</td></tr>`;
  };

  const head: string[] = [];
  head.push(`<div style="font-weight:bold">${escapeHtml(d.cafeName)}</div>`);
  head.push('<div style="font-weight:bold">Shift summary</div>');
  head.push(`<div>Opened: ${escapeHtml(formatDate(d.openedAt))}</div>`);
  head.push(`<div>Closed: ${escapeHtml(formatDate(d.closedAt))}</div>`);

  const rows: string[] = [];
  rows.push(row('Sales total', formatIDR(d.salesTotalIDR), true));
  rows.push(row('Cash sales', formatIDR(d.cashSalesIDR)));
  rows.push(row('QRIS sales', formatIDR(d.qrisSalesIDR)));
  rows.push(row('Opening float', formatIDR(d.openingFloatIDR)));
  rows.push(row('Expected cash', formatIDR(d.expectedCashIDR)));
  rows.push(
    row('Counted cash', d.countedCashIDR !== null ? formatIDR(d.countedCashIDR) : formatIDR(0))
  );
  rows.push(row('Variance', varianceText(d.varianceIDR)));

  return [
    '<div style="font-family:monospace;max-width:360px">',
    head.join(''),
    '<table cellspacing="0" cellpadding="2" width="100%">',
    rows.join(''),
    '</table>',
    '<div>Generated by kodapos</div>',
    '</div>',
  ].join('');
}
