import { convexTest } from 'convex-test';
import { describe, expect, it } from 'vitest';
import { api, internal } from '../../convex/_generated/api';
import type { Id } from '../../convex/_generated/dataModel';
import {
  buildShiftSummaryHtml,
  buildShiftSummaryText,
  type ShiftSummaryData,
} from '../../convex/lib/shiftSummary';
import schema from '../../convex/schema';

const modules = import.meta.glob('../../convex/**/*.*s');

function sampleData(overrides: Partial<ShiftSummaryData> = {}): ShiftSummaryData {
  return {
    cafeName: 'Kopi Senja',
    openedAt: 1700000000000,
    closedAt: 1700030000000,
    salesTotalIDR: 250000,
    cashSalesIDR: 180000,
    qrisSalesIDR: 70000,
    openingFloatIDR: 100000,
    expectedCashIDR: 280000,
    countedCashIDR: 282000,
    varianceIDR: 2000,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// buildShiftSummaryText / buildShiftSummaryHtml
// ---------------------------------------------------------------------------
describe('buildShiftSummaryText', () => {
  it('renders the headings, labels, formatted IDR, and a footer', () => {
    const text = buildShiftSummaryText(sampleData());
    expect(text).toContain('Kopi Senja');
    expect(text).toContain('Shift summary');
    expect(text).toContain('Sales');
    expect(text).toContain('Cash');
    expect(text).toContain('QRIS');
    expect(text).toContain('Expected');
    expect(text).toContain('Variance');
    expect(text).toContain('Rp 250.000');
    expect(text).toContain('Rp 180.000');
    expect(text).toContain('Generated by kodapos');
  });

  it('says "(Over)" for a positive variance', () => {
    const text = buildShiftSummaryText(sampleData({ varianceIDR: 2000 }));
    expect(text).toContain('(Over)');
    expect(text).not.toContain('(Short)');
  });

  it('says "(Short)" for a negative variance', () => {
    const text = buildShiftSummaryText(sampleData({ varianceIDR: -3000 }));
    expect(text).toContain('(Short)');
    expect(text).not.toContain('(Over)');
  });

  it('has no Over/Short suffix for a zero or null variance', () => {
    const zero = buildShiftSummaryText(sampleData({ varianceIDR: 0 }));
    expect(zero).not.toContain('(Over)');
    expect(zero).not.toContain('(Short)');
    const nul = buildShiftSummaryText(sampleData({ varianceIDR: null, countedCashIDR: null }));
    expect(nul).not.toContain('(Over)');
    expect(nul).not.toContain('(Short)');
  });

  it('contains no em-dash and no double-hyphen', () => {
    const text = buildShiftSummaryText(sampleData({ varianceIDR: -3000 }));
    expect(text).not.toContain('—');
    expect(text).not.toContain('--');
  });
});

describe('buildShiftSummaryHtml', () => {
  it('returns a table with the total and no em-dash or double-hyphen', () => {
    const html = buildShiftSummaryHtml(sampleData());
    expect(html).toContain('<table');
    expect(html).toContain('Rp 250.000');
    expect(html).not.toContain('—');
    expect(html).not.toContain('--');
  });
});

// ---------------------------------------------------------------------------
// settings.updateNotifications + get
// ---------------------------------------------------------------------------
describe('settings.updateNotifications', () => {
  it('persists notifications and get returns them', async () => {
    const t = convexTest(schema, modules);
    const userId = await t.run(async (ctx) =>
      ctx.db.insert('users', { name: 'Owner', email: 'o@x.com' })
    );
    const asOwner = t.withIdentity({ subject: `${userId}|test_session` });
    await asOwner.mutation(api.cafes.createForOwner, { name: 'Kopi Senja' });

    // Default before any update.
    const before = await asOwner.query(api.settings.get);
    expect(before.notifications.emailSummaryOnClose).toBe(false);

    await asOwner.mutation(api.settings.updateNotifications, {
      notifications: { summaryEmail: 'owner@example.com', emailSummaryOnClose: true },
    });

    const after = await asOwner.query(api.settings.get);
    expect(after.notifications.emailSummaryOnClose).toBe(true);
    expect(after.notifications.summaryEmail).toBe('owner@example.com');
  });
});

// ---------------------------------------------------------------------------
// shifts.summaryData (internalQuery)
// ---------------------------------------------------------------------------
describe('shifts.summaryData', () => {
  const OPENING = 100000;
  const ITEM_PRICE = 18000;

  it('returns the right numbers for a closed shift', async () => {
    const t = convexTest(schema, modules);
    const userId = await t.run(async (ctx) =>
      ctx.db.insert('users', { name: 'Owner', email: 'o@x.com' })
    );
    const asOwner = t.withIdentity({ subject: `${userId}|test_session` });
    await asOwner.mutation(api.cafes.createForOwner, { name: 'Kopi Senja' });
    await asOwner.mutation(api.cafes.updateProfile, {
      name: 'Kopi Senja',
      timezone: 'Asia/Jakarta',
      taxRatePct: 0,
      taxEnabled: false,
    });
    const cashierId = await asOwner.mutation(api.staff.create, { name: 'Andi', pin: '1234' });
    const shiftId = await asOwner.mutation(api.shifts.open, {
      cashierId,
      openingFloatIDR: OPENING,
    });
    const categoryId = await asOwner.mutation(api.menu.categories.create, { name: 'Kopi' });
    const itemId = await asOwner.mutation(api.menu.items.create, {
      categoryId,
      name: 'Espresso',
      priceIDR: ITEM_PRICE,
    });
    await asOwner.mutation(api.orders.createCashSale, {
      clientId: 's1',
      shiftId,
      cashierId,
      lines: [{ menuItemId: itemId, qty: 1, modifierOptionIds: [] as Id<'modifierOptions'>[] }],
      cashTenderedIDR: 20000,
      createdAtClient: 1,
    });
    // Close 2000 over.
    await asOwner.mutation(api.shifts.close, {
      id: shiftId,
      countedCashIDR: OPENING + ITEM_PRICE + 2000,
    });

    const d = await t.query(internal.shifts.summaryData, { shiftId });
    expect(d.cafeName).toBe('Kopi Senja');
    expect(d.salesTotalIDR).toBe(ITEM_PRICE);
    expect(d.cashSalesIDR).toBe(ITEM_PRICE);
    expect(d.qrisSalesIDR).toBe(0);
    expect(d.openingFloatIDR).toBe(OPENING);
    expect(d.expectedCashIDR).toBe(OPENING + ITEM_PRICE);
    expect(d.countedCashIDR).toBe(OPENING + ITEM_PRICE + 2000);
    expect(d.varianceIDR).toBe(2000);
    expect(d.closedAt).toEqual(expect.any(Number));
  });
});
