/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PosRouteImport } from './routes/_pos'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as PosPinRouteImport } from './routes/_pos/pin'
import { Route as PosDashboardRouteImport } from './routes/_pos/dashboard'
import { Route as PosShiftRouteRouteImport } from './routes/_pos/shift/route'
import { Route as PosSettingsRouteRouteImport } from './routes/_pos/settings/route'
import { Route as PosSaleRouteRouteImport } from './routes/_pos/sale/route'
import { Route as PosOnboardingRouteRouteImport } from './routes/_pos/onboarding/route'
import { Route as PosMenuRouteRouteImport } from './routes/_pos/menu/route'
import { Route as PosSaleIndexRouteImport } from './routes/_pos/sale/index'
import { Route as PosMenuIndexRouteImport } from './routes/_pos/menu/index'
import { Route as PosShiftOpenRouteImport } from './routes/_pos/shift/open'
import { Route as PosShiftCloseRouteImport } from './routes/_pos/shift/close'
import { Route as PosSettingsStaffRouteImport } from './routes/_pos/settings/staff'
import { Route as PosSettingsProfileRouteImport } from './routes/_pos/settings/profile'
import { Route as PosOnboardingProfileRouteImport } from './routes/_pos/onboarding/profile'
import { Route as PosOnboardingMenuRouteImport } from './routes/_pos/onboarding/menu'
import { Route as PosOnboardingCashierRouteImport } from './routes/_pos/onboarding/cashier'
import { Route as PosMenuModifiersRouteImport } from './routes/_pos/menu/modifiers'
import { Route as PosMenuCategoriesRouteImport } from './routes/_pos/menu/categories'
import { Route as PosMenuModifiersGroupIdRouteImport } from './routes/_pos/menu/modifiers.$groupId'
import { Route as PosMenuItemsItemIdRouteImport } from './routes/_pos/menu/items.$itemId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/_pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PosPinRoute = PosPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => PosRoute,
} as any)
const PosDashboardRoute = PosDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PosRoute,
} as any)
const PosShiftRouteRoute = PosShiftRouteRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => PosRoute,
} as any)
const PosSettingsRouteRoute = PosSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosRoute,
} as any)
const PosSaleRouteRoute = PosSaleRouteRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => PosRoute,
} as any)
const PosOnboardingRouteRoute = PosOnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PosRoute,
} as any)
const PosMenuRouteRoute = PosMenuRouteRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosRoute,
} as any)
const PosSaleIndexRoute = PosSaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosSaleRouteRoute,
} as any)
const PosMenuIndexRoute = PosMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosMenuRouteRoute,
} as any)
const PosShiftOpenRoute = PosShiftOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => PosShiftRouteRoute,
} as any)
const PosShiftCloseRoute = PosShiftCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => PosShiftRouteRoute,
} as any)
const PosSettingsStaffRoute = PosSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PosSettingsRouteRoute,
} as any)
const PosSettingsProfileRoute = PosSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PosSettingsRouteRoute,
} as any)
const PosOnboardingProfileRoute = PosOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PosOnboardingRouteRoute,
} as any)
const PosOnboardingMenuRoute = PosOnboardingMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosOnboardingRouteRoute,
} as any)
const PosOnboardingCashierRoute = PosOnboardingCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => PosOnboardingRouteRoute,
} as any)
const PosMenuModifiersRoute = PosMenuModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => PosMenuRouteRoute,
} as any)
const PosMenuCategoriesRoute = PosMenuCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PosMenuRouteRoute,
} as any)
const PosMenuModifiersGroupIdRoute = PosMenuModifiersGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => PosMenuModifiersRoute,
} as any)
const PosMenuItemsItemIdRoute = PosMenuItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => PosMenuRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/menu': typeof PosMenuRouteRouteWithChildren
  '/onboarding': typeof PosOnboardingRouteRouteWithChildren
  '/sale': typeof PosSaleRouteRouteWithChildren
  '/settings': typeof PosSettingsRouteRouteWithChildren
  '/shift': typeof PosShiftRouteRouteWithChildren
  '/dashboard': typeof PosDashboardRoute
  '/pin': typeof PosPinRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/menu/categories': typeof PosMenuCategoriesRoute
  '/menu/modifiers': typeof PosMenuModifiersRouteWithChildren
  '/onboarding/cashier': typeof PosOnboardingCashierRoute
  '/onboarding/menu': typeof PosOnboardingMenuRoute
  '/onboarding/profile': typeof PosOnboardingProfileRoute
  '/settings/profile': typeof PosSettingsProfileRoute
  '/settings/staff': typeof PosSettingsStaffRoute
  '/shift/close': typeof PosShiftCloseRoute
  '/shift/open': typeof PosShiftOpenRoute
  '/menu/': typeof PosMenuIndexRoute
  '/sale/': typeof PosSaleIndexRoute
  '/menu/items/$itemId': typeof PosMenuItemsItemIdRoute
  '/menu/modifiers/$groupId': typeof PosMenuModifiersGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/onboarding': typeof PosOnboardingRouteRouteWithChildren
  '/settings': typeof PosSettingsRouteRouteWithChildren
  '/shift': typeof PosShiftRouteRouteWithChildren
  '/dashboard': typeof PosDashboardRoute
  '/pin': typeof PosPinRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/menu/categories': typeof PosMenuCategoriesRoute
  '/menu/modifiers': typeof PosMenuModifiersRouteWithChildren
  '/onboarding/cashier': typeof PosOnboardingCashierRoute
  '/onboarding/menu': typeof PosOnboardingMenuRoute
  '/onboarding/profile': typeof PosOnboardingProfileRoute
  '/settings/profile': typeof PosSettingsProfileRoute
  '/settings/staff': typeof PosSettingsStaffRoute
  '/shift/close': typeof PosShiftCloseRoute
  '/shift/open': typeof PosShiftOpenRoute
  '/menu': typeof PosMenuIndexRoute
  '/sale': typeof PosSaleIndexRoute
  '/menu/items/$itemId': typeof PosMenuItemsItemIdRoute
  '/menu/modifiers/$groupId': typeof PosMenuModifiersGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pos': typeof PosRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_pos/menu': typeof PosMenuRouteRouteWithChildren
  '/_pos/onboarding': typeof PosOnboardingRouteRouteWithChildren
  '/_pos/sale': typeof PosSaleRouteRouteWithChildren
  '/_pos/settings': typeof PosSettingsRouteRouteWithChildren
  '/_pos/shift': typeof PosShiftRouteRouteWithChildren
  '/_pos/dashboard': typeof PosDashboardRoute
  '/_pos/pin': typeof PosPinRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_pos/menu/categories': typeof PosMenuCategoriesRoute
  '/_pos/menu/modifiers': typeof PosMenuModifiersRouteWithChildren
  '/_pos/onboarding/cashier': typeof PosOnboardingCashierRoute
  '/_pos/onboarding/menu': typeof PosOnboardingMenuRoute
  '/_pos/onboarding/profile': typeof PosOnboardingProfileRoute
  '/_pos/settings/profile': typeof PosSettingsProfileRoute
  '/_pos/settings/staff': typeof PosSettingsStaffRoute
  '/_pos/shift/close': typeof PosShiftCloseRoute
  '/_pos/shift/open': typeof PosShiftOpenRoute
  '/_pos/menu/': typeof PosMenuIndexRoute
  '/_pos/sale/': typeof PosSaleIndexRoute
  '/_pos/menu/items/$itemId': typeof PosMenuItemsItemIdRoute
  '/_pos/menu/modifiers/$groupId': typeof PosMenuModifiersGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/onboarding'
    | '/sale'
    | '/settings'
    | '/shift'
    | '/dashboard'
    | '/pin'
    | '/signin'
    | '/signup'
    | '/menu/categories'
    | '/menu/modifiers'
    | '/onboarding/cashier'
    | '/onboarding/menu'
    | '/onboarding/profile'
    | '/settings/profile'
    | '/settings/staff'
    | '/shift/close'
    | '/shift/open'
    | '/menu/'
    | '/sale/'
    | '/menu/items/$itemId'
    | '/menu/modifiers/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/shift'
    | '/dashboard'
    | '/pin'
    | '/signin'
    | '/signup'
    | '/menu/categories'
    | '/menu/modifiers'
    | '/onboarding/cashier'
    | '/onboarding/menu'
    | '/onboarding/profile'
    | '/settings/profile'
    | '/settings/staff'
    | '/shift/close'
    | '/shift/open'
    | '/menu'
    | '/sale'
    | '/menu/items/$itemId'
    | '/menu/modifiers/$groupId'
  id:
    | '__root__'
    | '/_pos'
    | '/_public'
    | '/_pos/menu'
    | '/_pos/onboarding'
    | '/_pos/sale'
    | '/_pos/settings'
    | '/_pos/shift'
    | '/_pos/dashboard'
    | '/_pos/pin'
    | '/_public/signin'
    | '/_public/signup'
    | '/_public/'
    | '/_pos/menu/categories'
    | '/_pos/menu/modifiers'
    | '/_pos/onboarding/cashier'
    | '/_pos/onboarding/menu'
    | '/_pos/onboarding/profile'
    | '/_pos/settings/profile'
    | '/_pos/settings/staff'
    | '/_pos/shift/close'
    | '/_pos/shift/open'
    | '/_pos/menu/'
    | '/_pos/sale/'
    | '/_pos/menu/items/$itemId'
    | '/_pos/menu/modifiers/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PosRoute: typeof PosRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos': {
      id: '/_pos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_pos/pin': {
      id: '/_pos/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PosPinRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/dashboard': {
      id: '/_pos/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PosDashboardRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/shift': {
      id: '/_pos/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof PosShiftRouteRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/settings': {
      id: '/_pos/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PosSettingsRouteRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/sale': {
      id: '/_pos/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof PosSaleRouteRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/onboarding': {
      id: '/_pos/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PosOnboardingRouteRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/menu': {
      id: '/_pos/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PosMenuRouteRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/sale/': {
      id: '/_pos/sale/'
      path: '/'
      fullPath: '/sale/'
      preLoaderRoute: typeof PosSaleIndexRouteImport
      parentRoute: typeof PosSaleRouteRoute
    }
    '/_pos/menu/': {
      id: '/_pos/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof PosMenuIndexRouteImport
      parentRoute: typeof PosMenuRouteRoute
    }
    '/_pos/shift/open': {
      id: '/_pos/shift/open'
      path: '/open'
      fullPath: '/shift/open'
      preLoaderRoute: typeof PosShiftOpenRouteImport
      parentRoute: typeof PosShiftRouteRoute
    }
    '/_pos/shift/close': {
      id: '/_pos/shift/close'
      path: '/close'
      fullPath: '/shift/close'
      preLoaderRoute: typeof PosShiftCloseRouteImport
      parentRoute: typeof PosShiftRouteRoute
    }
    '/_pos/settings/staff': {
      id: '/_pos/settings/staff'
      path: '/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof PosSettingsStaffRouteImport
      parentRoute: typeof PosSettingsRouteRoute
    }
    '/_pos/settings/profile': {
      id: '/_pos/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof PosSettingsProfileRouteImport
      parentRoute: typeof PosSettingsRouteRoute
    }
    '/_pos/onboarding/profile': {
      id: '/_pos/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof PosOnboardingProfileRouteImport
      parentRoute: typeof PosOnboardingRouteRoute
    }
    '/_pos/onboarding/menu': {
      id: '/_pos/onboarding/menu'
      path: '/menu'
      fullPath: '/onboarding/menu'
      preLoaderRoute: typeof PosOnboardingMenuRouteImport
      parentRoute: typeof PosOnboardingRouteRoute
    }
    '/_pos/onboarding/cashier': {
      id: '/_pos/onboarding/cashier'
      path: '/cashier'
      fullPath: '/onboarding/cashier'
      preLoaderRoute: typeof PosOnboardingCashierRouteImport
      parentRoute: typeof PosOnboardingRouteRoute
    }
    '/_pos/menu/modifiers': {
      id: '/_pos/menu/modifiers'
      path: '/modifiers'
      fullPath: '/menu/modifiers'
      preLoaderRoute: typeof PosMenuModifiersRouteImport
      parentRoute: typeof PosMenuRouteRoute
    }
    '/_pos/menu/categories': {
      id: '/_pos/menu/categories'
      path: '/categories'
      fullPath: '/menu/categories'
      preLoaderRoute: typeof PosMenuCategoriesRouteImport
      parentRoute: typeof PosMenuRouteRoute
    }
    '/_pos/menu/modifiers/$groupId': {
      id: '/_pos/menu/modifiers/$groupId'
      path: '/$groupId'
      fullPath: '/menu/modifiers/$groupId'
      preLoaderRoute: typeof PosMenuModifiersGroupIdRouteImport
      parentRoute: typeof PosMenuModifiersRoute
    }
    '/_pos/menu/items/$itemId': {
      id: '/_pos/menu/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/menu/items/$itemId'
      preLoaderRoute: typeof PosMenuItemsItemIdRouteImport
      parentRoute: typeof PosMenuRouteRoute
    }
  }
}

interface PosMenuModifiersRouteChildren {
  PosMenuModifiersGroupIdRoute: typeof PosMenuModifiersGroupIdRoute
}

const PosMenuModifiersRouteChildren: PosMenuModifiersRouteChildren = {
  PosMenuModifiersGroupIdRoute: PosMenuModifiersGroupIdRoute,
}

const PosMenuModifiersRouteWithChildren =
  PosMenuModifiersRoute._addFileChildren(PosMenuModifiersRouteChildren)

interface PosMenuRouteRouteChildren {
  PosMenuCategoriesRoute: typeof PosMenuCategoriesRoute
  PosMenuModifiersRoute: typeof PosMenuModifiersRouteWithChildren
  PosMenuIndexRoute: typeof PosMenuIndexRoute
  PosMenuItemsItemIdRoute: typeof PosMenuItemsItemIdRoute
}

const PosMenuRouteRouteChildren: PosMenuRouteRouteChildren = {
  PosMenuCategoriesRoute: PosMenuCategoriesRoute,
  PosMenuModifiersRoute: PosMenuModifiersRouteWithChildren,
  PosMenuIndexRoute: PosMenuIndexRoute,
  PosMenuItemsItemIdRoute: PosMenuItemsItemIdRoute,
}

const PosMenuRouteRouteWithChildren = PosMenuRouteRoute._addFileChildren(
  PosMenuRouteRouteChildren,
)

interface PosOnboardingRouteRouteChildren {
  PosOnboardingCashierRoute: typeof PosOnboardingCashierRoute
  PosOnboardingMenuRoute: typeof PosOnboardingMenuRoute
  PosOnboardingProfileRoute: typeof PosOnboardingProfileRoute
}

const PosOnboardingRouteRouteChildren: PosOnboardingRouteRouteChildren = {
  PosOnboardingCashierRoute: PosOnboardingCashierRoute,
  PosOnboardingMenuRoute: PosOnboardingMenuRoute,
  PosOnboardingProfileRoute: PosOnboardingProfileRoute,
}

const PosOnboardingRouteRouteWithChildren =
  PosOnboardingRouteRoute._addFileChildren(PosOnboardingRouteRouteChildren)

interface PosSaleRouteRouteChildren {
  PosSaleIndexRoute: typeof PosSaleIndexRoute
}

const PosSaleRouteRouteChildren: PosSaleRouteRouteChildren = {
  PosSaleIndexRoute: PosSaleIndexRoute,
}

const PosSaleRouteRouteWithChildren = PosSaleRouteRoute._addFileChildren(
  PosSaleRouteRouteChildren,
)

interface PosSettingsRouteRouteChildren {
  PosSettingsProfileRoute: typeof PosSettingsProfileRoute
  PosSettingsStaffRoute: typeof PosSettingsStaffRoute
}

const PosSettingsRouteRouteChildren: PosSettingsRouteRouteChildren = {
  PosSettingsProfileRoute: PosSettingsProfileRoute,
  PosSettingsStaffRoute: PosSettingsStaffRoute,
}

const PosSettingsRouteRouteWithChildren =
  PosSettingsRouteRoute._addFileChildren(PosSettingsRouteRouteChildren)

interface PosShiftRouteRouteChildren {
  PosShiftCloseRoute: typeof PosShiftCloseRoute
  PosShiftOpenRoute: typeof PosShiftOpenRoute
}

const PosShiftRouteRouteChildren: PosShiftRouteRouteChildren = {
  PosShiftCloseRoute: PosShiftCloseRoute,
  PosShiftOpenRoute: PosShiftOpenRoute,
}

const PosShiftRouteRouteWithChildren = PosShiftRouteRoute._addFileChildren(
  PosShiftRouteRouteChildren,
)

interface PosRouteChildren {
  PosMenuRouteRoute: typeof PosMenuRouteRouteWithChildren
  PosOnboardingRouteRoute: typeof PosOnboardingRouteRouteWithChildren
  PosSaleRouteRoute: typeof PosSaleRouteRouteWithChildren
  PosSettingsRouteRoute: typeof PosSettingsRouteRouteWithChildren
  PosShiftRouteRoute: typeof PosShiftRouteRouteWithChildren
  PosDashboardRoute: typeof PosDashboardRoute
  PosPinRoute: typeof PosPinRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosMenuRouteRoute: PosMenuRouteRouteWithChildren,
  PosOnboardingRouteRoute: PosOnboardingRouteRouteWithChildren,
  PosSaleRouteRoute: PosSaleRouteRouteWithChildren,
  PosSettingsRouteRoute: PosSettingsRouteRouteWithChildren,
  PosShiftRouteRoute: PosShiftRouteRouteWithChildren,
  PosDashboardRoute: PosDashboardRoute,
  PosPinRoute: PosPinRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface PublicRouteChildren {
  PublicSigninRoute: typeof PublicSigninRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSigninRoute: PublicSigninRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PosRoute: PosRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
