/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PosRouteImport } from './routes/_pos'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as PosDashboardRouteImport } from './routes/_pos/dashboard'
import { Route as PosOnboardingRouteRouteImport } from './routes/_pos/onboarding/route'
import { Route as PosOnboardingProfileRouteImport } from './routes/_pos/onboarding/profile'
import { Route as PosOnboardingMenuRouteImport } from './routes/_pos/onboarding/menu'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/_pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PosDashboardRoute = PosDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PosRoute,
} as any)
const PosOnboardingRouteRoute = PosOnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PosRoute,
} as any)
const PosOnboardingProfileRoute = PosOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PosOnboardingRouteRoute,
} as any)
const PosOnboardingMenuRoute = PosOnboardingMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosOnboardingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/onboarding': typeof PosOnboardingRouteRouteWithChildren
  '/dashboard': typeof PosDashboardRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/onboarding/menu': typeof PosOnboardingMenuRoute
  '/onboarding/profile': typeof PosOnboardingProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/onboarding': typeof PosOnboardingRouteRouteWithChildren
  '/dashboard': typeof PosDashboardRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/onboarding/menu': typeof PosOnboardingMenuRoute
  '/onboarding/profile': typeof PosOnboardingProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pos': typeof PosRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_pos/onboarding': typeof PosOnboardingRouteRouteWithChildren
  '/_pos/dashboard': typeof PosDashboardRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_pos/onboarding/menu': typeof PosOnboardingMenuRoute
  '/_pos/onboarding/profile': typeof PosOnboardingProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/onboarding/menu'
    | '/onboarding/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/onboarding/menu'
    | '/onboarding/profile'
  id:
    | '__root__'
    | '/_pos'
    | '/_public'
    | '/_pos/onboarding'
    | '/_pos/dashboard'
    | '/_public/signin'
    | '/_public/signup'
    | '/_public/'
    | '/_pos/onboarding/menu'
    | '/_pos/onboarding/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PosRoute: typeof PosRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos': {
      id: '/_pos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_pos/dashboard': {
      id: '/_pos/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PosDashboardRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/onboarding': {
      id: '/_pos/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PosOnboardingRouteRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/onboarding/profile': {
      id: '/_pos/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof PosOnboardingProfileRouteImport
      parentRoute: typeof PosOnboardingRouteRoute
    }
    '/_pos/onboarding/menu': {
      id: '/_pos/onboarding/menu'
      path: '/menu'
      fullPath: '/onboarding/menu'
      preLoaderRoute: typeof PosOnboardingMenuRouteImport
      parentRoute: typeof PosOnboardingRouteRoute
    }
  }
}

interface PosOnboardingRouteRouteChildren {
  PosOnboardingMenuRoute: typeof PosOnboardingMenuRoute
  PosOnboardingProfileRoute: typeof PosOnboardingProfileRoute
}

const PosOnboardingRouteRouteChildren: PosOnboardingRouteRouteChildren = {
  PosOnboardingMenuRoute: PosOnboardingMenuRoute,
  PosOnboardingProfileRoute: PosOnboardingProfileRoute,
}

const PosOnboardingRouteRouteWithChildren =
  PosOnboardingRouteRoute._addFileChildren(PosOnboardingRouteRouteChildren)

interface PosRouteChildren {
  PosOnboardingRouteRoute: typeof PosOnboardingRouteRouteWithChildren
  PosDashboardRoute: typeof PosDashboardRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosOnboardingRouteRoute: PosOnboardingRouteRouteWithChildren,
  PosDashboardRoute: PosDashboardRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface PublicRouteChildren {
  PublicSigninRoute: typeof PublicSigninRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSigninRoute: PublicSigninRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PosRoute: PosRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
